const SELECT_RFC = "SELECT_RFC"
const SELECT_CHASSIS = "SELECT_CHASSIS"
const SELECT_PROMOTER = "SELECT_PROMOTER"
const SELECT_RBS = "SELECT_RBS"
export const builderConstants = {
    SELECT_RFC,
    SELECT_CHASSIS,
    SELECT_PROMOTER,
    SELECT_RBS
}
