const SELECT_RFC = "SELECT_RFC"
const SELECT_CHASSIS = "SELECT_CHASSIS"
const SELECT_PROMOTER = "SELECT_PROMOTER"
export const builderConstants = {
    SELECT_RFC,
    SELECT_CHASSIS,
    SELECT_PROMOTER
}
